---
- name: maultiple installation
  hosts: all
  become: yes
  tasks:
    - name: Multiple installation
      apt:
        name: "{{ item }}"
        state: latest
      loop:
         - curl
         - vim


